export const products = [
	{
		id: 1,
		name: "Apple iPhone 15 Pro",
		price: 127990.0,
		original: 134900.0,
		discount: "5%",
		rating: 4.6,
		reviews: 1200,
		description:
			"FORGED IN TITANIUM — iPhone 15 Pro has a strong and light aerospace-grade titanium design with a textured matte-glass back. It also features a Ceramic Shield front that’s tougher than any smartphone glass. And it’s splash, water, and dust resistant.",
		category: "electronics",
	},
	{
		id: 2,
		name: "Realme Buds T200 Lite",
		price: 1339,
		original: 1999,
		discount: "30%",
		rating: 4.0,
		reviews: 683,
		description:
			"The realme Buds T200 Lite TWS is the ultimate companion for those who want to level up their audio game. With a powerful 12.4mm Dynamic Bass Driver, you'll experience rich, deep bass that will make your music come alive. And with a whopping 48 hours of total playback, you can jam out all day and all night without worrying about running out of juice. Thanks to dual-mic AI Deep Call Noise Cancellation, you can enjoy crystal-clear calls even in the midst of chaos. Need a quick charge? No problem! Just 10 minutes will give you 5 hours of playback, perfect for those on-the-go moments. These earbuds are also super smooth for gaming and video watching with their Ultra-Low Latency feature. And with IPX4 water resistance, you can take them to the gym, on a run, or even out in the rain without worry.",
		category: "electronics",
	},
	{
		id: 3,
		name: "realme P2 Pro 5G",
		price: 16499,
		original: 25999,
		discount: "36%",
		rating: 4.2,
		reviews: 1141,
		description:
			"Experience unparalleled visual brilliance with the realme P2 Pro’s 120Hz Curved AMOLED Display. This screen boasts a bright and eye-friendly technology, ensuring vibrant colours and deep contrasts for an immersive viewing experience. This display features a high dynamic photo technology, it delivers stunning clarity and lifelike details, making every image and video come alive with remarkable precision and brightness. Whether you’re gaming, streaming, or Browse, enjoy a display that sets a new standard for excellence.",
		category: "electronics",
	},
	{
		id: 4,
		name: "Samsung Galaxy S24 Ultra 5G",
		price: 129999.0,
		original: 134999.0,
		discount: "4%",
		rating: 4.4,
		reviews: 548,
		description:
			"Meet Galaxy S24 Ultra, the ultimate form of Galaxy Ultra with a new titanium exterior and a 17.25cm (6.8') flat display. It's an absolute marvel of design. The legacy of Galaxy Note is alive and well. Write, tap and navigate with precision your fingers wish they had on the new, flat display.",
		category: "electronics",
	},
	{
		id: 5,
		name: "boAt Airdopes 141",
		price: 1299.0,
		original: 4490.0,
		discount: "71%",
		rating: 4.1,
		reviews: 150000,
		description:
			"Enjoy an extended break on weekends with your favourite episodes on stream, virtue of a playback time of up to 42 hours including the 6 hours nonstop playtime for earbuds. Frequency 20Hz-20KHz. Our BEAST mode makes these true wireless earbuds a partner in entertainment with real-time audio and low latency experience.",
		category: "electronics",
	},
	{
		id: 6,
		name: "HP Laptop 15s",
		price: 38990.0,
		original: 52405.0,
		discount: "26%",
		rating: 4.1,
		reviews: 1254,
		description:
			"Power through your day with an Intel Core i5 processor, 8GB RAM, and a 512GB SSD. Enjoy the vibrant 15.6-inch Full HD display and the convenience of a backlit keyboard.",
		category: "electronics",
	},
	{
		id: 7,
		name: "Amazon Echo Dot (4th Gen)",
		price: 3499.0,
		original: 4499.0,
		discount: "22%",
		rating: 4.4,
		reviews: 85000,
		description:
			"Our most popular smart speaker with a sleek, compact design that fits perfectly into small spaces. It delivers crisp vocals and balanced bass for full sound you can enjoy anywhere in your home.",
		category: "electronics",
	},
	{
		id: 8,
		name: "Sony Bravia 55-inch 4K TV",
		price: 57990.0,
		original: 99900.0,
		discount: "42%",
		rating: 4.7,
		reviews: 11254,
		description:
			"Experience breathtaking 4K picture quality with the X1 4K processor. See stunningly natural colors, exceptional clarity, and incredible contrast on this Google TV.",
		category: "electronics",
	},
	{
		id: 9,
		name: "OnePlus Nord CE 3 Lite 5G",
		price: 17999.0,
		original: 19999.0,
		discount: "10%",
		rating: 4.3,
		reviews: 125000,
		description:
			"A Bigger, Bolder, More Colorful Display. A 108 MP camera system that captures more light, for more detailed and realistic photos. And 67W SUPERVOOC fast charging that gives you a day's power in just 30 minutes.",
		category: "electronics",
	},
	{
		id: 10,
		name: "Fire-Boltt Phoenix Pro",
		price: 1499.0,
		original: 9999.0,
		discount: "85%",
		rating: 4.2,
		reviews: 95000,
		description:
			"1.39' HD Display Smartwatch with Bluetooth Calling, 120+ Sports Modes, and a durable metal body. Track your health with SpO2 and Heart Rate Monitoring.",
		category: "electronics",
	},
	{
		id: 11,
		name: "Nilkamal Freedom Cabinet",
		price: 3499.0,
		original: 5100.0,
		discount: "31%",
		rating: 4.1,
		reviews: 18500,
		description:
			"A compact and durable storage cabinet with 1 adjustable shelf. Perfect for organizing your home or office space. Made from high-quality polypropylene.",
		category: "furniture",
	},
	{
		id: 12,
		name: "Wakefit Study Table",
		price: 2891.0,
		original: 5163.0,
		discount: "44%",
		rating: 4.4,
		reviews: 8500,
		description:
			"Ergonomically designed study table with a spacious tabletop and a convenient drawer for storage. Made from engineered wood with a sleek finish.",
		category: "furniture",
	},
	{
		id: 13,
		name: "Green Soul Ergonomic Chair",
		price: 8990.0,
		original: 18590.0,
		discount: "52%",
		rating: 4.4,
		reviews: 23000,
		description:
			"A high-back mesh office chair with 3D adjustable armrests, lumbar support, and a synchro-tilt mechanism for ultimate comfort during long work hours.",
		category: "furniture",
	},
	{
		id: 14,
		name: "Sleepyhead Sofa Bed",
		price: 13999.0,
		original: 19999.0,
		discount: "30%",
		rating: 4.3,
		reviews: 4500,
		description:
			"A versatile 3-seater sofa bed that easily converts into a comfortable bed. Features a sturdy wooden frame and soft fabric upholstery.",
		category: "furniture",
	},
	{
		id: 15,
		name: "DeckUp Plank Book Shelf",
		price: 2499.0,
		original: 5000.0,
		discount: "50%",
		rating: 4.0,
		reviews: 9500,
		description:
			"A modern and stylish 4-tier bookshelf with a unique design. Perfect for displaying books, decorative items, and more. Made from engineered wood.",
		category: "furniture",
	},
	{
		id: 16,
		name: "The Sleep Company Mattress",
		price: 18999.0,
		original: 24999.0,
		discount: "24%",
		rating: 4.6,
		reviews: 11000,
		description:
			"Experience the SmartGRID technology that provides 2X more back support and a cooling comfort. This orthopedic mattress is designed for a restful sleep.",
		category: "furniture",
	},
	{
		id: 17,
		name: "IKEA LACK Wall Shelf",
		price: 1299.0,
		original: 1799.0,
		discount: "28%",
		rating: 4.5,
		reviews: 32000,
		description:
			"A simple and classic floating wall shelf that becomes one with the wall thanks to the concealed mounting hardware. Perfect for a clean, minimalist look.",
		category: "furniture",
	},
	{
		id: 18,
		name: "Solimo Coffee Table",
		price: 2799.0,
		original: 6000.0,
		discount: "53%",
		rating: 4.1,
		reviews: 12000,
		description:
			"A contemporary coffee table with a premium walnut finish and a lower shelf for extra storage. Made from high-grade engineered wood.",
		category: "furniture",
	},
	{
		id: 19,
		name: "Cello Novelty Big Cupboard",
		price: 4999.0,
		original: 7000.0,
		discount: "29%",
		rating: 4.0,
		reviews: 15000,
		description:
			"A spacious and sturdy plastic cupboard with multiple shelves, ideal for storing clothes, books, and other household items.",
		category: "furniture",
	},
	{
		id: 20,
		name: "Durian Leatherette Recliner",
		price: 22990.0,
		original: 41500.0,
		discount: "45%",
		rating: 4.3,
		reviews: 1800,
		description:
			"Sink into the plush comfort of this single-seater manual recliner. Upholstered in premium leatherette with a sturdy wooden frame.",
		category: "furniture",
	},
	{
		id: 21,
		name: "Levi's Men's 512 Jeans",
		price: 1799.0,
		original: 3599.0,
		discount: "50%",
		rating: 4.3,
		reviews: 25000,
		description:
			"A modern slim fit with room to move, the 512 Slim Taper Jean is a classic that works for every occasion. Made with Levi's Flex for maximum comfort.",
		category: "clothing",
	},
	{
		id: 22,
		name: "Allen Solly Men's Polo",
		price: 749.0,
		original: 1299.0,
		discount: "42%",
		rating: 4.1,
		reviews: 35000,
		description:
			"A classic solid polo T-shirt made from 100% cotton. Features a regular fit and a ribbed collar and cuffs for a timeless look.",
		category: "clothing",
	},
	{
		id: 23,
		name: "Van Heusen Men's Formal Shirt",
		price: 999.0,
		original: 1799.0,
		discount: "44%",
		rating: 4.2,
		reviews: 18000,
		description:
			"A slim-fit formal shirt crafted from a premium cotton blend. Perfect for the office or any formal occasion, offering both style and comfort.",
		category: "clothing",
	},
	{
		id: 24,
		name: "Jockey Men's T-Shirt",
		price: 549.0,
		original: 699.0,
		discount: "21%",
		rating: 4.3,
		reviews: 45000,
		description:
			"A classic crew-neck t-shirt made from super combed cotton rich fabric. Provides a comfortable fit and is ideal for everyday wear.",
		category: "clothing",
	},
	{
		id: 25,
		name: "Puma Men's Track Pants",
		price: 1299.0,
		original: 2499.0,
		discount: "48%",
		rating: 4.1,
		reviews: 12000,
		description:
			"Comfortable and stylish track pants with an elasticated waistband and Puma branding. Perfect for workouts or casual wear.",
		category: "clothing",
	},
	{
		id: 26,
		name: "U.S. Polo Assn. Men's Shirt",
		price: 1199.0,
		original: 2199.0,
		discount: "45%",
		rating: 4.2,
		reviews: 22000,
		description:
			"A classic checked casual shirt made from 100% cotton. Features a regular fit and the iconic U.S. Polo Assn. logo.",
		category: "clothing",
	},
	{
		id: 27,
		name: "Wrangler Men's Denim Jacket",
		price: 2499.0,
		original: 4999.0,
		discount: "50%",
		rating: 4.4,
		reviews: 8500,
		description:
			"A timeless denim jacket with a classic design and a comfortable fit. Made from durable cotton denim, perfect for layering.",
		category: "clothing",
	},
	{
		id: 28,
		name: "Tommy Hilfiger Men's T-Shirt",
		price: 1099.0,
		original: 1999.0,
		discount: "45%",
		rating: 4.3,
		reviews: 15000,
		description:
			"A premium crew-neck t-shirt with the iconic Tommy Hilfiger flag logo embroidery. Made from soft and breathable organic cotton.",
		category: "clothing",
	},
	{
		id: 29,
		name: "Peter England Men's Trousers",
		price: 1149.0,
		original: 2299.0,
		discount: "50%",
		rating: 4.0,
		reviews: 13000,
		description:
			"A pair of slim-fit casual trousers made from a comfortable cotton stretch fabric. A versatile addition to any man's wardrobe.",
		category: "clothing",
	},
	{
		id: 30,
		name: "Jack & Jones Men's Hoodie",
		price: 1499.0,
		original: 2999.0,
		discount: "50%",
		rating: 4.2,
		reviews: 9500,
		description:
			"A comfortable and stylish hooded sweatshirt with a printed design. Perfect for a casual and laid-back look.",
		category: "clothing",
	},
	{
		id: 31,
		name: "Adidas Men's Running Shoes",
		price: 2499.0,
		original: 4999.0,
		discount: "50%",
		rating: 4.2,
		reviews: 18000,
		description:
			"Lightweight and comfortable running shoes with a breathable mesh upper and a durable rubber outsole for excellent grip.",
		category: "footwear",
	},
	{
		id: 32,
		name: "Puma Men's Sneakers",
		price: 1999.0,
		original: 3999.0,
		discount: "50%",
		rating: 4.1,
		reviews: 22000,
		description:
			"Classic casual sneakers with a synthetic leather upper and the iconic Puma formstrip. A versatile choice for everyday wear.",
		category: "footwear",
	},
	{
		id: 33,
		name: "Nike Men's Revolution 6",
		price: 3199.0,
		original: 3695.0,
		discount: "13%",
		rating: 4.3,
		reviews: 25000,
		description:
			"Made with at least 20% recycled content by weight, this running shoe offers a soft ride with a foam midsole and a comfortable fit.",
		category: "footwear",
	},
	{
		id: 34,
		name: "Reebok Men's Walking Shoes",
		price: 1499.0,
		original: 2999.0,
		discount: "50%",
		rating: 4.0,
		reviews: 15000,
		description:
			"Comfortable and supportive walking shoes with a MemoryTech foam sockliner for superior cushioning and a durable outsole.",
		category: "footwear",
	},
	{
		id: 35,
		name: "Bata Men's Formal Shoes",
		price: 899.0,
		original: 1299.0,
		discount: "31%",
		rating: 4.0,
		reviews: 11000,
		description:
			"Classic and elegant formal lace-up shoes made from synthetic material. A perfect choice for office wear and formal occasions.",
		category: "footwear",
	},
	{
		id: 36,
		name: "Woodland Men's Leather Boots",
		price: 2899.0,
		original: 4295.0,
		discount: "33%",
		rating: 4.3,
		reviews: 13000,
		description:
			"Rugged and durable outdoor boots made from genuine leather with a thick rubber sole for excellent traction and support.",
		category: "footwear",
	},
	{
		id: 37,
		name: "Crocs Men's Clogs",
		price: 1999.0,
		original: 3495.0,
		discount: "43%",
		rating: 4.5,
		reviews: 45000,
		description:
			"Incredibly light and fun to wear, these clogs are water-friendly and buoyant. The pivoting heel strap offers a secure fit.",
		category: "footwear",
	},
	{
		id: 38,
		name: "Red Tape Men's Loafers",
		price: 1399.0,
		original: 4899.0,
		discount: "71%",
		rating: 4.0,
		reviews: 9500,
		description:
			"Stylish and comfortable slip-on loafers made from genuine leather with a cushioned footbed for all-day comfort.",
		category: "footwear",
	},
	{
		id: 39,
		name: "Campus Men's Sports Shoes",
		price: 999.0,
		original: 1699.0,
		discount: "41%",
		rating: 4.1,
		reviews: 14000,
		description:
			"Trendy and comfortable sports shoes with a durable mesh upper and a phylon sole for lightweight cushioning.",
		category: "footwear",
	},
	{
		id: 40,
		name: "Hush Puppies Men's Sandals",
		price: 1599.0,
		original: 2999.0,
		discount: "47%",
		rating: 4.2,
		reviews: 7500,
		description:
			"Comfortable and stylish leather sandals with a cushioned footbed and a flexible sole. Perfect for casual summer days.",
		category: "footwear",
	},
	{
		id: 41,
		name: "Ikigai by Hector Garcia",
		price: 349.0,
		original: 650.0,
		discount: "46%",
		rating: 4.6,
		reviews: 75000,
		description:
			"The Japanese secret to a long and happy life. This international bestseller helps you find your purpose and live a more fulfilling life.",
		category: "books",
	},
	{
		id: 42,
		name: "Atomic Habits by James Clear",
		price: 499.0,
		original: 799.0,
		discount: "38%",
		rating: 4.7,
		reviews: 95000,
		description:
			"An easy and proven way to build good habits and break bad ones. Learn how to make small, incremental changes that lead to remarkable results.",
		category: "books",
	},
	{
		id: 43,
		name: "The Psychology of Money",
		price: 389.0,
		original: 599.0,
		discount: "35%",
		rating: 4.6,
		reviews: 65000,
		description:
			"Timeless lessons on wealth, greed, and happiness. Morgan Housel shares 19 short stories exploring the strange ways people think about money.",
		category: "books",
	},
	{
		id: 44,
		name: "Rich Dad Poor Dad by Robert T. Kiyosaki",
		price: 350.0,
		original: 699.0,
		discount: "50%",
		rating: 4.6,
		reviews: 85000,
		description:
			"What the rich teach their kids about money that the poor and middle class do not. It advocates the importance of financial literacy.",
		category: "books",
	},
	{
		id: 45,
		name: "The Alchemist by Paulo Coelho",
		price: 250.0,
		original: 399.0,
		discount: "37%",
		rating: 4.7,
		reviews: 125000,
		description:
			"A classic novel about a shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure.",
		category: "books",
	},
	{
		id: 46,
		name: "Sapiens: A Brief History of Humankind",
		price: 450.0,
		original: 799.0,
		discount: "44%",
		rating: 4.7,
		reviews: 55000,
		description:
			"Yuval Noah Harari's groundbreaking book explores the history of our species, from the Stone Age to the Silicon Age.",
		category: "books",
	},
	{
		id: 47,
		name: "The Intelligent Investor by Benjamin Graham",
		price: 599.0,
		original: 999.0,
		discount: "40%",
		rating: 4.6,
		reviews: 35000,
		description:
			"The definitive book on value investing. A timeless classic that provides a framework for making sound investment decisions.",
		category: "books",
	},
	{
		id: 48,
		name: "To Kill a Mockingbird by Harper Lee",
		price: 299.0,
		original: 450.0,
		discount: "34%",
		rating: 4.8,
		reviews: 45000,
		description:
			"A classic of modern American literature, this novel explores the injustice of racial prejudice in the American South.",
		category: "books",
	},
	{
		id: 49,
		name: "Word Power Made Easy by Norman Lewis",
		price: 149.0,
		original: 250.0,
		discount: "40%",
		rating: 4.5,
		reviews: 95000,
		description:
			"The most effective vocabulary builder in the English language. It helps you understand and remember words through their etymology.",
		category: "books",
	},
	{
		id: 50,
		name: "Grandma's Bag of Stories by Sudha Murty",
		price: 199.0,
		original: 299.0,
		discount: "33%",
		rating: 4.7,
		reviews: 35000,
		description:
			"A delightful collection of stories that captures the simplicity and wisdom of life in a small town. A perfect read for children and adults alike.",
		category: "books",
	},
	{
		id: 51,
		name: "Optimum Nutrition (ON) Gold Standard Whey",
		price: 5499.0,
		original: 7299.0,
		discount: "25%",
		rating: 4.4,
		reviews: 45000,
		description:
			"24g of whey protein per serving with whey protein isolates as the primary ingredient. Helps build and maintain muscle when taken over time with regular resistance training.",
		category: "health",
	},
	{
		id: 52,
		name: "Himalaya Wellness Pure Herbs Tulasi",
		price: 180.0,
		original: 200.0,
		discount: "10%",
		rating: 4.3,
		reviews: 25000,
		description:
			"Helps suppress cough and aids the mobilization of mucus. A natural immunity booster that supports respiratory health.",
		category: "health",
	},
	{
		id: 53,
		name: "Dabur Chyawanprash",
		price: 350.0,
		original: 425.0,
		discount: "18%",
		rating: 4.4,
		reviews: 35000,
		description:
			"A time-tested Ayurvedic formulation of more than 41 Ayurvedic herbs that aid in boosting the immune system, thereby protecting the body from everyday infections.",
		category: "health",
	},
	{
		id: 54,
		name: "Protinex Health And Nutritional Drink",
		price: 550.0,
		original: 645.0,
		discount: "15%",
		rating: 4.3,
		reviews: 18000,
		description:
			"A vegetarian ready-to-serve beverage mix that helps in bridging the protein gap in the diet. Contains 25 vital nutrients to support strength and immunity.",
		category: "health",
	},
	{
		id: 55,
		name: "HealthKart HK Vitals Fish Oil",
		price: 449.0,
		original: 849.0,
		discount: "47%",
		rating: 4.2,
		reviews: 22000,
		description:
			"1000 mg fish oil with 180 mg EPA and 120 mg DHA. Helps support joint, heart, brain, and eye health.",
		category: "health",
	},
	{
		id: 56,
		name: "Tata 1mg Multivitamin",
		price: 499.0,
		original: 995.0,
		discount: "50%",
		rating: 4.1,
		reviews: 15000,
		description:
			"A comprehensive blend of vitamins, minerals, and ginseng extract to support overall health, immunity, and energy levels.",
		category: "health",
	},
	{
		id: 57,
		name: "Accu-Chek Active Blood Glucose Meter",
		price: 999.0,
		original: 1649.0,
		discount: "39%",
		rating: 4.4,
		reviews: 55000,
		description:
			"An easy-to-use blood glucose monitor that provides accurate results in just 5 seconds. Comes with 10 test strips.",
		category: "health",
	},
	{
		id: 58,
		name: "Colgate Charcoal Clean Toothpaste",
		price: 250.0,
		original: 320.0,
		discount: "22%",
		rating: 4.5,
		reviews: 45000,
		description:
			"Infused with activated charcoal and mint, this toothpaste provides deep cleaning and a fresh breath experience.",
		category: "health",
	},
	{
		id: 59,
		name: "Dettol Antiseptic Liquid",
		price: 320.0,
		original: 357.0,
		discount: "10%",
		rating: 4.6,
		reviews: 65000,
		description:
			"A proven safe and effective concentrated antiseptic disinfectant that kills bacteria and provides protection against germs.",
		category: "health",
	},
	{
		id: 60,
		name: "MuscleBlaze Creatine Monohydrate",
		price: 649.0,
		original: 949.0,
		discount: "32%",
		rating: 4.3,
		reviews: 28000,
		description:
			"Helps increase strength, power, and muscle mass by increasing the body's creatine stores. Made with 100% pure creatine monohydrate.",
		category: "health",
	},
];
